default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        stages: [pre-commit]
        args: ["--maxkb=1000"]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: forbid-new-submodules
        stages: [pre-commit]
      - id: check-builtin-literals
        stages: [pre-commit]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        exclude: >
          (?x)^(
            fixtures/.*| icon.png | large_icon.png
          )$
      - id: git-dirty
        stages: [pre-commit]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
        stages: [pre-commit]
      - id: remove-crlf
        stages: [pre-commit]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        stages: [pre-commit]
