default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        stages: [pre-commit]
        require_serial: false
        args: ["--maxkb=1000"]
      - id: check-case-conflict
        stages: [pre-commit]
        require_serial: false
      - id: check-merge-conflict
        stages: [pre-commit]
        require_serial: false
      - id: detect-private-key
        stages: [pre-commit]
        require_serial: false
      - id: forbid-new-submodules
        stages: [pre-commit]
        require_serial: false
      - id: check-builtin-literals
        stages: [pre-commit]
        require_serial: false

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        stages: [pre-commit]
        exclude: >
          (?x)^(
            fixtures/.*| icon.png | large_icon.png
          )$
      - id: git-dirty
        stages: [pre-commit]
        require_serial: false

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
        stages: [pre-commit]
        require_serial: false
      - id: remove-crlf
        stages: [pre-commit]
        require_serial: false

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
        require_serial: false

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        stages: [pre-commit]
        require_serial: false
